connect/urls.py
"""Connect base url definitions."""
# pylint: disable=no-value-for-parameter,invalid-name
from urlparse import urljoin

from allauth.account import views as auth_views
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.http import HttpResponse
from django.views.generic import RedirectView, TemplateView
from django_bouncy.views import endpoint as bouncy_endpoint
import autocomplete_light

from open_connect.accounts.views import SignupView as ConnectSignupView
from open_connect.groups.views import GroupListView

autocomplete_light.autodiscover()
admin.site.login = login_required(admin.site.login)
admin.autodiscover()


urlpatterns = patterns(
    '',
    url(r'^$', include('open_connect.welcome.urls')),
    url(r'^admin/', include(admin.site.urls)),

    # Because we're overriding django-allauth's signup view with our own view
    # we need to include it above the include for django-allatuh
    url(r'^user/signup/$',
        ConnectSignupView.as_view(),
        name='account_signup'),
    url(r'^user/', include('allauth.urls')),

    url(r'^connect/', include('private_connect.urls')),
    url(r'^accounts/', include('open_connect.accounts.urls')),
    url(r'^groups/', include('open_connect.groups.urls')),
    url(r'^messages/', include('open_connect.connectmessages.urls')),
    url(r'^moderation/', include('open_connect.moderation.urls')),
    url(r'^mail/bouncy/$',
        bouncy_endpoint,
        name='ses_endpoint'),
    url(r'^mail/', include('open_connect.mailer.urls')),
    url(r'^subscriptions/',
        include('open_connect.notifications.urls')),
    url(r'^media/', include('open_connect.media.urls')),
    url(r'^robots\.txt$',
        lambda r: HttpResponse(
            "User-agent: *\nDisallow: /", content_type="text/plain")),
    # pylint: disable=line-too-long
    url(r'^favicon\.ico$',
        RedirectView.as_view(
            url=urljoin(settings.STATIC_URL, 'img/favicon.ico'),
            permanent=True)),
    url(r'^autocomplete/', include('autocomplete_light.urls')),
    url(r'^reports/', include('open_connect.reporting.urls')),
    url(r'^explore/$', GroupListView.as_view(), name='explore'),
    url(r'^terms-and-conditions/$',
        TemplateView.as_view(template_name='terms_and_code_of_conduct.html'),
        name='terms_and_conditions'),
    url(r'^resources/', include('open_connect.resources.urls')),
    url(r'^api/', include('connect_api.urls')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

open_connect/groups/urls.py
"""Group urls."""
# pylint: disable=invalid-name,no-value-for-parameter
from django.contrib.auth.decorators import permission_required
from django.conf.urls import patterns, url

from open_connect.groups import views


urlpatterns = patterns(
    'groups.views',
    url(r'^create/$',
        permission_required('groups.add_group', raise_exception=True)(
            views.GroupCreateView.as_view()
        ),
        name="create_group"),
    url(r'^(?P<pk>\d+)/update/$',
        views.GroupUpdateView.as_view(),
        name='update_group'),
    url(r'^(?P<pk>\d+)/delete/$',
        permission_required('groups.delete_group', raise_exception=True)(
            views.GroupDeleteView.as_view()
        ),
        name='delete_group'),
    url(r'^(?P<group_id>\d+)/images/$',
        views.GroupImagesView.as_view(),
        name='group_images'),
    url(r'^(?P<pk>\d+)/$',
        views.GroupDetailView.as_view(),
        name='group_details'),
    url(r'^(?P<pk>\d+)/members/$',
        views.GroupMemberListView.as_view(),
        name='group_members'),
    url(r'^(?P<pk>\d+)/invite/$', permission_required('accounts.add_invite')(
        views.GroupMemberInviteView.as_view()),
        name='group_invite'),
    url(r'^(?P<group_id>\d+)/quickadd/$',
        permission_required('accounts.add_invite')(views.group_quick_user_add),
        name='group_quick_user_add'),
    url(r'^$', views.GroupListView.as_view(), name='groups'),
    url(r'^my-groups/$', views.MyGroupsView.as_view(), name='my_groups'),
    url(r'^subscribe/$', views.group_subscribe_view, name='group_subscribe'),
    url(r'^unsubscribe/$',
        views.group_unsubscribe_view,
        name='group_unsubscribe'),
    url(r'^moderate-requests/$',
        views.GroupRequestUpdateView.as_view(),
        name='moderate_requests'),
    url(r'^(?P<group_id>\d+)/remove-user-from-group/(?P<user_uuid>[\d\w-]+)/$',
        views.remove_user_from_group_view,
        name='remove_user_from_group'),

)

open_connect/groups/models.py
"""Group models."""
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group as AuthGroup, Permission
from django.core.cache import cache
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models import Q
from django.db.models.signals import m2m_changed
from django.utils.safestring import mark_safe
from taggit.managers import TaggableManager
from taggit.models import Tag
import autocomplete_light

from open_connect.media.models import Image, ShortenedURL
from open_connect.connectmessages.models import Thread, Message
from open_connect.connect_core.utils.location import get_coordinates, STATES
from open_connect.connect_core.utils.models import TimestampModel
from open_connect.groups.tasks import remove_user_from_group


autocomplete_light.register(Tag)

GROUP_STATUSES = (
    ('active', 'Active'),
    ('deleted', 'Deleted')
)


class Category(TimestampModel):
    """Group Category"""
    slug = models.SlugField(unique=True)
    name = models.CharField(max_length=127)
    color = models.CharField(
        verbose_name='Category Color', max_length=7, default='#000000')

    class Meta(object):
        """Meta options for Category model"""
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'


    def __unicode__(self):
        """Unicode Representation of Category"""
        return self.name



class GroupManager(models.Manager):
    """Manager for Group model."""
    def get_queryset(self):
        """
        Ensures that all queries fror groups also queries the auth group
        model
        """
        return super(GroupManager, self).get_queryset().select_related(
            'group', 'category').exclude(status='deleted')

    def with_deleted(self):
        """Includes deleted groups."""
        return super(GroupManager, self).get_queryset().select_related(
            'group', 'category')

    # pylint: disable=no-self-use
    def create(self, **kwargs):
        """Create a new group."""
        name = kwargs.pop('name', None)
        if 'group' not in kwargs and name:
            kwargs['group'] = AuthGroup.objects.create(name=name)
        return super(GroupManager, self).create(**kwargs)

    def published(self, **kwargs):
        """Get published groups."""
        return self.get_queryset().filter(published=True, **kwargs)

    def search(self, search=None, location=None):
        """Groups search"""
        groups = Group.objects.published().select_related('image', 'group')
        if search:
            groups = groups.filter(
                Q(group__name__icontains=search)
                | Q(category__name__icontains=search)
                | Q(description__icontains=search)
                | Q(tags__slug__icontains=search)
            ).distinct()

        if location:
            groups = self.location_search(location, queryset=groups)

        return groups

    def location_search(self, location, queryset=None):
        """Groups search by location."""
        coords = get_coordinates(location)

        # If no coordinates are provided, return an empty queryset
        if not coords:
            return Group.objects.none()

        if queryset is None:
            queryset = Group.objects.published()

        # Pass the job of finding distance to the database using this query
        sql = (
            'SELECT '
            '(degrees(acos( '
            'sin(radians(latitude)) '
            '* sin(radians(%s)) '
            '+ cos(radians(latitude)) '
            '* cos(radians(%s)) '
            '* cos(radians(longitude - %s) ) '
            ') ) * 69.09)'
        )

        result = queryset.extra(
            select={'distance': sql},
            select_params=(coords[0], coords[0], coords[1]),

            # We use the same SQL again to do filtering by distance and
            # radius. We cannot use the param in the `SELECT` because
            # of a postgres limitation
            where=['(' + sql + ') <= "groups_group"."radius"'],
            params=(coords[0], coords[0], coords[1]),

            order_by=['-featured', 'distance', 'group__name']
        ).distinct()

        return result


class Group(TimestampModel):
    """Group model."""
    group = models.OneToOneField(AuthGroup)
    private = models.BooleanField(
        default=False,
        help_text='Membership to private groups is moderated.'
    )
    published = models.BooleanField(
        default=True,
        verbose_name=u'Publish this group',
        help_text='Published groups can be seen by all users.'
                  ' Unpublished groups can only be seen if'
                  ' you have the link.'
    )
    moderated = models.BooleanField(
        default=False,
        verbose_name=u'Moderate this group',
        help_text='Posts by users must be moderated by an admin.'
    )
    featured = models.BooleanField(
        default=False,
        verbose_name=u'This is an official group',
        help_text='Official groups are managed by staff and '
                  'appear first in search results.',
        db_index=True
    )
    member_list_published = models.BooleanField(
        default=True,
        help_text='Group member list is public'
    )
    category = models.ForeignKey(
        'groups.Category', verbose_name=u'Category', default=1)
    display_location = models.CharField(blank=True, max_length=100)
    latitude = models.FloatField(blank=True, null=True)
    longitude = models.FloatField(blank=True, null=True)
    radius = models.IntegerField(blank=True, null=True)
    is_national = models.BooleanField(default=True, db_index=True)
    # owners get permissions using a receiver below: group_owners_changed
    owners = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        blank=True,
        related_name='owned_groups_set')
    whitelist_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        blank=True,
        related_name='whitelist_set'
    )
    description = models.TextField(blank=True)
    tags = TaggableManager(blank=True)
    image = models.ForeignKey(Image, blank=True, null=True)
    state = models.CharField(
        max_length=3,
        choices=[(s, s) for s in STATES],
        blank=True,
        db_index=True
    )
    tos_accepted_at = models.DateTimeField(blank=True, null=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, null=True)
    status = models.CharField(
        choices=GROUP_STATUSES,
        default='active',
        db_index=True,
        max_length=50
    )

    objects = GroupManager()

    class Meta(object):
        # pylint: disable=no-init,too-few-public-methods
        """Group meta options."""
        ordering = ['-featured', '-is_national', 'group__name']
        permissions = (
            ('can_edit_any_group', 'Can edit any group.'),
            ('can_edit_group_category', 'Can change a group\'s category.'),
            ('can_edit_group_featured',
             'Can change a group\'s featured status.'),
        )

    def __unicode__(self):
        """Convert group to a unicode string."""
        return u'%s' % self.group.name

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        """Override save to auto-set is_national."""
        if not all([self.longitude, self.latitude, self.radius]):
            self.is_national = True
        else:
            self.is_national = False

        return super(Group, self).save(
            force_insert, force_update, using, update_fields)

    def delete(self, using=None):
        """Don't actually delete."""
        self.status = 'deleted'
        self.save()
        for user in self.group.user_set.all().iterator():
            remove_user_from_group.delay(user=user, group=self)

    def get_absolute_url(self):
        """Get the full local URL of an object"""
        return reverse('group_details', args=(self.pk,))

    @property
    def full_url(self):
        """The URL (including the origin) of the group detail page"""
        return settings.ORIGIN + self.get_absolute_url()

    def clean(self):
        """Custom group validation."""
        required_together = [
            self.latitude, self.longitude, self.radius]
        if any(required_together) and not all(required_together):
            raise ValidationError(
                "If a location is specified, name, latitude,"
                " longitude, and radius are required."
            )

    def get_members(self):
        """Return a queryset of all users in the group."""
        return self.group.user_set.all()

    def get_members_avatar_prioritized(self):
        """Return a queryset of group members prioritizing those with avatars"""
        # Selecting null as an extra column and sorting on that column
        # to preserve sorting when switching between MySQL and PostgreSQL.
        return self.get_members().extra(
            select={'image_null': 'image_id is null'}
        ).select_related('image').order_by('image_null')

    def public_threads_by_user(self, user):
        """All approved threads sent to group that the user is allowed to see"""
        return Thread.public.by_user(user).filter(group=self)

    def public_threads(self):
        """All the threads sent to this group."""
        return Thread.public.by_group(group=self)

    @property
    def unmoderated_messages(self):
        """
        Return all unmoderated messages
        """
        return Message.objects.filter(
            thread__group=self,
            status__in=['pending', 'flagged'],
            sender__is_banned=False)

    @property
    def total_unmoderated_messages(self):
        """
        Returns the total number of unmoderated messages
        """
        return self.unmoderated_messages.count()

    def images(self, user):
        """Returns popular images related to this group."""

open_connect/groups/templates/groups/group_content.html
{% load static %}
{% for group in groups %}
    {% if profile_is_self or not group.private %}

    <div class="item border{% if group.featured %} official{% endif %}{% if group.is_national %} national{% endif %} {{group.category.slug}}" data-official="{% if group.featured %}true{%else%}false{% endif %}" data-national="{% if group.is_national %}true{%else%}false{% endif %}" data-category="{{ group.category.slug }}" data-id="{{group.id}}">

        {% if group.featured %}<span class="right-banner">Official</span>{% endif %}
        <header class="item-info">

            <div>
                <h2>
                    <a href="{% url "group_details" group.pk %}">{{ group.group.name |truncatechars:40}}</a>
                </h2>
                <p class="item-desc">
                    {{ group.description|truncatechars:72|safe }}
                </p>
            </div>
        </header>

        {% comment %}

            {% if group.distance %}<p><small>{{ group.distance|floatformat:1 }} miles away</small></p>{% endif %}
            {% with group.tags.all as tags %}
                {% include "groups/tags_embed.html" %}
            {% endwith %}

        {% endcomment %}
        <div class="item-image">
            <a href="{% url "group_details" group.pk %}" style="{% if group.image %}background:url({{ group.image.get_display_image.url }}) no-repeat center;background-size:cover;{% endif %}">
                {{ group.group.name }} Group Image
            </a>
        </div>


        {% comment %}-------- STATUS ------{% endcomment %}

        {% if not request.user.is_authenticated and not group.private %}
        <div class="item-status admin">
            <a href="{% url "group_details" group.pk %}">Join Group</a>
        </div>
        {% else %}

        {% if group.pk in subscribed_ids %}
            {% comment %}  Is the user in the group?  {% endcomment %}
            {% if user.is_superuser or group.pk in moderating_ids and perms.groups.change_group %}
                {% comment %}  Is the user an admin ?  {% endcomment %}
                <div class="item-status admin">
                    <a href="{% url "group_details" group.pk %}">Group admin</a>
                </div>
            {% else %}
                {% comment %}  Non-admin member  {% endcomment %}
                {% comment %}  Unsub only from profile page  {% endcomment %}
                {% if profile_is_self %}
                    <div class="item-status leave member leave-group-{{ group.pk }}">
                        <div class="inner">
                            <input type="button" class="btn btn-large btn-link leave-group" data-group-id="{{ group.pk }}" value="Leave Group" />
                        </div>
                    </div>
                {% else %}
                    {% comment %}  Else, just show status  {% endcomment %}
                    <div class="item-status member">
                        <a href="{% url "group_details" group.pk %}">Group member</a>
                    </div>
                {% endif %}
            {% endif %}

        {% elif group.id in requested_ids %}

            <div class="item-status pending">
                <a href="{% url "group_details" group.pk %}">Pending approval</a>
            </div>

        {% else %}

            <div class="item-status not-member join-group-{{ group.pk }}">
                <div>
                    <input type="button" class="btn btn-link btn-large join-group" data-group-id="{{ group.pk }}" value="Join Group" />
                </div>
            </div>


        {% endif %}
        {% endif %}

    </div>
    {% endif %}
{% endfor %}

open_connect/groups/templates/groups/group_delete.html
{% extends "base.html" %}
{% load static %}

{% block title %}Deleting {{group}}{% endblock %}

{% block content_header %}{% endblock %}
{% block page_content %}
    <h4 class="{{group.category.slug}}"> <a href="{% url "group_details" pk=group.pk %}">{{group}}</a></h4>
    <h1>Delete {{ group }}</h1>
    <div class="group-container">
    <form method="post">
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary submit-form">
        {% csrf_token %}
    </form>
    </div>

{% endblock %}

{% block js_default %}
{% if not USE_MINIFY %}
    {{ block.super }}
{% endif %}
{% endblock %}

open_connect/groups/templates/groups/group_form.html
{% extends "base.html" %}
{% load static %}

{% block bodyclass %}group-form{% endblock bodyclass %}

{% block title %}{% if group.pk %}Update {{ group }}{% else %}Create a group{% endif %}{% endblock %}

{% block content_header %}{% endblock %}

{% block page_content %}
    <form method="POST" enctype="multipart/form-data" class="form-horizontal">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">{% if group %}<h1>Edit {{ group }}</h1>{% else %}<h1>Create a group</h1>{% endif %}</div>
        </div>
        <div class="row">
            <div class="col-md-5 col-md-offset-1">
                {% with authgroup_form as form %}
                    {% include "common/form_snippet.html" %}
                {% endwith %}
                {% with group_form as form %}
                    {% if form.non_field_errors %}<div class="alert alert-error">{{ form.non_field_errors|join:", " }}</div>{% endif %}
                    {% for field in form %}
                        {% if forloop.counter <= 4 %}
                            {% include "common/form_field.html" %}
                        {% endif %}
                    {% endfor %}
                {% endwith %}

                <div class="form-group">
                    <label>Location</label>
                </div>
                <div class="form-group">
                    <div class="styled-checkbox">
                        <input id="location_toggle" name="location_toggle" type="checkbox" checked>
                        <label for="location_toggle">This group has a location</label>
                    </div>
                </div>


            </div>

            {% comment %}
  background:url(){% else %}background:url(){% endif %}
{% endcomment %}


            <div class="col-md-4 col-md-offset-1">
                {% with image_form as form %}
                    {% for field in form %}
                        <label for="id_{{ field.html_name }}">{{ field.label }}{% if field.field.required %}<span class="req">*</span>{% endif %}</label>
                        <div class="clearfix fileinput {% if group.image %}fileinput-exists{% else %}fileinput-new{% endif %}" data-provides="fileinput">
                            <div class="fileinput-preview thumbnail" data-trigger="fileinput">
                                {% if not group.image %}<div class="default"></div>{% endif %}
                                {% if group.image %}<img src="{% url "custom_image_version" image_uuid=group.image.uuid image_type="thumbnail" %}">{% endif %}
                            </div>
                            <div>
                                <span class="help-block">Choose an image to use as the group's profile picture.</span>
                              <span class="btn btn-primary btn-file">
                                  <span class="fileinput-new">Select image</span>
                                  <span class="fileinput-exists">Change</span>
                                  {{field}}
                              </span>
                            </div>
                        </div>
                    {% endfor %}
                {% endwith %}
                {% with group_form as form %}
                    {% if form.non_field_errors %}<div class="alert alert-error">{{ form.non_field_errors|join:", " }}</div>{% endif %}
                    {% for field in form %}
                        {% if forloop.counter > 4 %}
                            {% include "common/form_field.html" %}
                        {% endif %}
                    {% endfor %}
                {% endwith %}
            </div>
        </div>
        <div class="row">
            <div class="col-md-5 col-md-offset-1">
                <div class="form-group address form-location">
                    <label>Address</label>
                    <div class="input-group">
                        <input type="text" id="id_group_form-address" class="form-control">
                          <span class="input-group-btn">
                            <button class="btn btn-primary" type="button">Go</button>
                          </span>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-md-offset-1">
                <div class="form-group radius form-location">
                    <label>Coverage radius, in miles</label>
                    <div class="input-group input-group-stacked spinner">
                        <input type="text" class="form-control">
                          <span class="input-group-btn">
                            <a class="btn btn-link up" id="up">Increase</a>
                            <a class="btn btn-link down" id="down">Decrease</a>
                          </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-10 col-md-offset-1">

                <div id="map_canvas" class="form-location"></div>
                <small class="form-location">You can drag points on the circle to modify the group's radius.</small>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="form-actions">
                    {% if group.pk and perms.groups.delete_group %}<a class="col-md-2 col-md-push-3" href="{% url "delete_group" pk=group.pk %}">Delete group</a>{% endif %}<input type="submit" name="submit" value="{% if not group %}Create group{% else %}Save changes{% endif %}" class="btn btn-primary submit-form"/>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

{% block js_default%}
    <script id="alertTemplate" type="text/html">
    {% templatetag openvariable %}=[[ ]]={% templatetag closevariable %}
    <div class="alert alert-dismissable alert-success alert-new hidden"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>[[message]]</div>
</script>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    {{ block.super }}
    <script type="text/javascript">
        {% if group %}
            var isNew = false;
        {% else %}
            var isNew = true;
        {% endif %}
    </script>
{% if USE_MINIFY %}
        <script type="text/javascript" src="{% static 'js/newgroup.min.js' %}"></script>
    {% else %}
        <script type="text/javascript" src="{% static 'js/modules/Spinner.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/modules/Map.js' %}"></script>
    {% endif %}
    {% include 'autocomplete_light/static.html' %}
    <script>
        $(function(){
            $('#id_group_form-description').redactor({
                minHeight: 300,
                buttons: ['bold', 'italic', '|', 'link'],
                allowedTags: ['br', 'a', 'em', 'strong'],
                linebreaks: true
            });
        });
    </script>
{% endblock %}

open_connect/groups/templates/groups/group_images.html
{% extends "base.html" %}
{% load static %}

{% block bodyclass %}group-gallery isotope-list cards{% endblock bodyclass %}

{% block title %}Images posted to {{ group }}{% endblock %}

{% block page_title %}
    {{ group }} gallery
{% endblock page_title %}

{% block title_action %}
    {% include "media/db-buttons.html" %}
{% endblock title_action %}

{% block page_content %}

  <div class="col-md-12">
    {% include "media/db-actions.html" %}
      {% include "common/pagination.html" %}
      <div class="gallery-container">
            {% include "media/gallery-image.html" %}
      </div>
      {% include "common/pagination.html" %}
      {% csrf_token %}</div>
{% endblock %}

{% block js_default %}
<script type="text/javascript" src="https://www.dropbox.com/static/api/1/dropins.js" id="dropboxjs" data-app-key="nx53b6nt2ais248"></script>

{% if USE_MINIFY %}
    <script src="{% static 'connect/js/gallery.min.js' %}"></script>
{% else %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'magnific-popup/dist/jquery.magnific-popup.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'isotope/jquery.isotope.min.js' %}"></script>
    <script src="{% static 'js/modules/js/Isogroup.js' %}"></script>
    <script src="{% static 'js/sections/gallery.js' %}"></script>
    <script src="{% static 'js/modules/dropbox-saver.js' %}"></script>
{% endif %}

<script type="text/javascript">

// Promote / demote images
$(document).ready(function () {
    
    var csrfmiddlewaretoken = $("[name='csrfmiddlewaretoken']").val();

    function demote_image(uuid) {
        $.post("{% url "demote_image" %}", {'uuid': uuid, csrfmiddlewaretoken: csrfmiddlewaretoken}, function(data) {
            $(".promotion-" + uuid).html('The image has been demoted');
        });
    }

    function promote_image(uuid) {
        $.post("{% url "promote_image" %}", {'uuid': uuid, csrfmiddlewaretoken: csrfmiddlewaretoken}, function(data) {
            $(".promotion-" + uuid).html('The image has been promoted');
        });
    }

    $(".demote-image").click(function() {
        demote_image(this.id);
        ga('send', 'event', 'Gallery Action', 'Image demoted', this.id);
    });

    $(".promote-image").click(function() {
        promote_image(this.id);
        ga('send', 'event', 'Gallery Action', 'Image promoted', this.id);
    });
});
</script>    

{% endblock %}

open_connect/groups/templates/groups/group_invite.html
{% extends "admin_base.html" %}

{% block title %}Invite To {{ group }}{% endblock %}

{% block page_title %}
    Invite To {{ group }}
{% endblock page_title %}

{% block main_area %}
    {% if verify %}
        <div class="confirminvites">
            {% if existing %}
            <h3>These users will be added to {{ group }}:</h3>
            <ul>
                {% for record in existing %}
                    <li>{{ record }} {{ record.email }}</li>
                {% endfor %}
            </ul>
            {% endif %}

            {% if new %}
            <h3>The following email addresses will receive invites to join {{ brand_title }} and will be added to {{ group }} on their first login:</h3>
            <ul>
                {% for address in new %}
                    <li>{{ address }}</li>
                {% endfor %}
            </ul>
            {% endif %}

        </div>
    {% endif %}
    <form method="POST" {% if form.is_multipart %}enctype="multipart/form-data" {% endif %}class="form-horizontal">
        <div class="inviteform" {% if verify %}style="display: none"{% endif %}>
            {% include "common/horizontal_form_snippet.html" %}
        </div>
        <div class="form-actions">
            <input type="submit" name="submit" value="Invite" class="btn btn-primary"/>
            {% if verify %}
                <a class="redo btn btn-warning" href="#">Make A Change</a>
            {% endif %}
        </div>
    </form>

{% endblock %}

{% block js_default %}
    {{ block.super }}
    <script type="text/javascript">
        $('.redo').click(function(event){
            event.preventDefault();
            $('.inviteform').toggle();
            $('.redo').toggle();
            $('.confirminvites').toggle();
            $('#id_verified').remove();
        })
    </script>
{% endblock js_default %}

open_connect/groups/templates/groups/group_member_list_member_snippet.html
{% load static %}
<div class="item border">
                {% if group_member.is_staff %}<span class="staff">
                    STAFF<span class="badge"></span>MEMBER
                    </span>{% endif %}
    <div class="item-image">
        <a href="{{ group_member.get_absolute_url }}" {% if group_member.image %}style="background:url({% url 'custom_image_version' group_member.image.uuid 'display_image' %}) no-repeat;background-size:cover;"{% endif %}></a>
    </div>
    <section class="item-info">
        <div>
            <ul class="actions">
                <li>
                    <a class="compose" href="{% url "create_direct_message" group_member.uuid %}"><i class="{{icon_prefix}}envelope"></i><span class="sr-only">Contact</span></a>
                </li>
                {% if user_is_owner %}
                    <li>
                        <a class="remove" href="{% url "remove_user_from_group" group_id=group.pk user_uuid=group_member.uuid %}"><i class="{{icon_prefix}}remove-circle"></i><span class="sr-only">Remove</span></a>
                    </li>
                {% endif %}
            </ul>
            <a href="{{ group_member.get_absolute_url }}">{{ group_member }}</a>

        </div>
    </section>
</div>